### ISSUE TITLE
Installation (*.msi) is incompete

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#1038]
I have compared current `*.msi` file with previous release(last `.NET Framework`): https://github.com/uxmal/reko/releases/tag/version-0.9.3
 - [ ] `decompile.exe` is absent
 - [ ]  `COPYING` is absent
 - [ ] There are unnecessary `*.pdb` files
 - [ ] Unnecessary `NUnit3.TestAdapter.*`, `nunit.engine.*`
 - [ ] Unnecessary `*.deps.json`
 - [ ] Unnecessary `*.dll.config`
 - [ ] Unnecessary `c2xml.exe`, `genPICdb.exe`, `xslt.exe`, `testhost.exe`

**Comment by ptomin** [comment]
Possible fix: fd3d8e2

**Comment by smx-smx** [comment]
I was discussing with @uxmal about this.
I was thinking about a similar solution to yours, he was thinking about bringing the file list from the previous build system back.
I'll let him comment about this

**Comment by smx-smx** [comment]
My opinion is that a separate .csproj is a good idea, and mimics the same structure as the `Runtime` csproj (which is used to build the nuget package)
In a `WixRuntime` csproj we can define what goes in the output directory and what doesn't.

The generator tool, `specGen`, simply considers whatever is in the outDir of the project (same logic used for the nuget package aswell - Runtime.csproj)

Rather than changing the tool too much, we could control that with build targets or options in WixRuntime.csproj

**Comment by ptomin** [comment]
> Rather than changing the tool too much, we could control what we want in the final package by using build targets or flags in WixRuntime.csproj

Good point. I was going to modify `specGen` to ignore `*.pdb` and `*.json.deps`. Instead, I'm modifying `WixRuntime` to delete this files after build.

**Comment by uxmal** [comment]
Commit 678825c4f9ba47fe4a77709989fd12899c8533ea finally addresses this. Thanks everyone for your patience.
