### ISSUE TITLE
windows?

### ISSUE THREAD

**Issue by vpolinov** [uxmal/reko#1044]
Author,

If you mention windows, make sure you not only mention it in your readme but also provide comprehensive instruction to run it.

If you do not provide instructions - make sure you do not mention windows.

Hope, the idea is clear to you.

**Comment by uxmal** [comment]
@vpolinov : thanks for your feedback. It's a little unclear what your asking for. Reko is a work in progress, and certainly the documentation is lacking. Are you looking for instructions how to install Reko? They're referred to in the README as well as here:
https://github.com/uxmal/reko/blob/master/doc/guide/reko.md

A "quickstart" to show how to use the program is here:
https://github.com/uxmal/reko/blob/master/doc/guide/quickstart.md

A more in-depth guide is naturally the ultimate goal, but hasn't received much attention due to lack of time. Is there anything in particular you'd like to know more about? A focused "How do i do X?"  question is easier to address than "windows?"
