### ISSUE TITLE
Closing About Decompiler UI with Enter crashes Reko

### ISSUE THREAD

**Issue by ErickDaGamer** [uxmal/reko#1096]
By clicking on Help>About Decompiler and closing with Enter crashes the entire program.

![image](https://user-images.githubusercontent.com/59941851/142969538-8e83c266-0fb5-4e08-ba4f-5fe2700731ad.png)

[crash.log](https://github.com/uxmal/reko/files/7585766/crash.log)

Clicking OK works though

This is also broken in version 0.10.1.0

**Comment by uxmal** [comment]
Thanks for reporting this. It turns out that when opened, the About dialog has the link to `https://github.com/uxmal/reko` focused. When you hit `<Enter>`, it tries to navigate to the link. Unfortunately, there is a bug in link navigation logic, which I've now fixed. I've also changed the initial focus of the About dialog to be the `OK` button, so that hitting `<Enter>` (or `<Esc>` for that matter) dismisses the dialog.

I wish they were all this easy to fix!
