### ISSUE TITLE
can't load the DOS game binary driver

### ISSUE THREAD

**Issue by LowLevelMahn** [uxmal/reko#1109]
i tried Reko with the Stunts MT32 sound driver (some sort of DOS dll)

my reverse engineering project:
https://github.com/LowLevelMahn/UnifiedMT15
the driver binary (~1kb)
https://github.com/LowLevelMahn/UnifiedMT15/blob/main/org/10/MT15.DRV

there is a jump table starting at offset 0 (https://github.com/LowLevelMahn/UnifiedMT15/blob/0d3458cc35712e03990b7837683eff9385dcbda2/MT15.asm#L204)

but the import stops with unknown format error
its a x86/80186 realmode, 16 bit, segment/offset code

**Comment by uxmal** [comment]
The DRV file is a raw blob of binary x86 code. There no MZ header or any other metadata available for Reko to make sense of it. To make headway you can provide Reko with information about the binary. If you're using the GUI client, you can fill in the following values:

![image](https://user-images.githubusercontent.com/10154465/146203199-8d6b9d04-1fe1-4339-8da9-ceb037a24bdd.png)

Then, when the binary is loaded, you need to help Reko by identifying some possible code locations, since no metadata hints are forthcoming. The beginning of the DRV is a bunch of near JMP instructions (opcode 0xE9). IF you select `Edit > Find` and search for the 0xE9 in your program image:
![image](https://user-images.githubusercontent.com/10154465/146204923-a9d89e92-fea1-42af-a95c-cb317c34c7bc.png)
you will get the following hits:
![image](https://user-images.githubusercontent.com/10154465/146205133-173e7571-faec-4d0c-aa2a-33cf53980995.png)
Now select the relevant hits, which will be all except the last two, and right-click on them to show the context menu, and select `Mark as procedure entry`:
![image](https://user-images.githubusercontent.com/10154465/146205326-16d36b9b-32df-438e-89f3-db371098a9d3.png)
Now Reko has some procedures to chew on. You can press the `Finish Decompilation` button to see what the decompilation process produced.

**Comment by uxmal** [comment]
I've attached the resulting .dcproject here:
[MT15.zip](https://github.com/uxmal/reko/files/7720355/MT15.zip)

**Comment by LowLevelMahn** [comment]
that worked! thanks

will Reko allow pure binary loading with code at offset 0 in the future?

**Comment by uxmal** [comment]
I'm not 100% sure what you mean, perhaps you could elaborate on what you'd like to happen. 

When Reko fails to identify the file format, it depends on the user to specify the base address (see ```Load binary at address```) above. You can of course specify `0000:0000` as the base address. However, the DRV file you have is not meant to be loaded at address `0000:0000`. That address is reserved in x86 real mode for the interrupt table. It consists of an array of 256 `far` pointers. which is incompatible with the sequence of `jmp` instructions in the beginning of the DRV file.

**Comment by LowLevelMahn** [comment]
> I'm not 100% sure what you mean, perhaps you could elaborate on what you'd like to happen.
> 
> When Reko fails to identify the file format, it depends on the user to specify the base address (see `Load binary at address`) above. You can of course specify `0000:0000` as the base address. However, the DRV file you have is not meant to be loaded at address `0000:0000`. That address is reserved in x86 real mode for the interrupt table. It consists of an array of 256 `far` pointers. which is incompatible with the sequence of `jmp` instructions in the beginning of the DRV file.

i understand that 0:0 is a bad place for absolute loading
my idea was some sort of a virtual segment + the 0 offset as code start

so as a additonal feature to just absolute segments

Load binary at address: LoadSeg:0

i think something similar already happens with dos exe programs in Reko (which also can not be loaded at a decent address)

but not super needed - it works as it is

**Comment by uxmal** [comment]
Closing as resolved.
