### ISSUE TITLE
Hitachi H8 postincrement missing

### ISSUE THREAD

**Issue by systemloc** [uxmal/reko#1242]
Short sample code in Hitachi H8 arch demonstrating that the generated pseudocode is missing a postincrement in a mov op that acts as a loop iterator

[Bugreport.125.2.zip](https://github.com/uxmal/reko/files/10499698/Bugreport.125.2.zip)

**Comment by uxmal** [comment]
The reason why this is happening is because Reko pessimistically assumes that after a call to an unknown procedure, all registers are trashed. In your sample binary, the call in question is an indirect call, and Reko has no way of determining its target address. So it assumes the worst, that all registers are trashed.

In most binaries generated by a compiler adhere to an ABI; sometimes hand-written assembler programs will violate ABI's. Sometimes a platform doesn't have a well-defined ABI (looking at you, MS-DOS). It seems that this should a user option `Assume calls respect platform ABI`.

**Comment by uxmal** [comment]
Commit b1a6a2d672866b6c28f5cc13b78c8c352315f7a8 exhibits that increment statement. Other issues have materialized but one thing at a time!
