### ISSUE TITLE
"An internal error occurred. Index was outside the bounds of the array." when attempting to load Keen 1

### ISSUE THREAD

**Issue by juj** [uxmal/reko#1290]
Downloading Keen Version 1.1 from https://keenwiki.shikadi.net/wiki/Keen_1_Versions  ( http://cd.textfiles.com/wildcatgold/games/1keen.zip ) and opening it in Reko gives the following:

![image](https://github.com/uxmal/reko/assets/225351/6390df72-2932-40e0-b8bc-306fb9fbfee7)

It reads like Reko is at least attempting to identify and process LZ compressed executables, but then gets confused.

Manually unpacking via https://keenwiki.shikadi.net/wiki/UNLZEXE does seem to work around.

**Comment by uxmal** [comment]
This was fixed in commit 61bbcfa. You can use the CI build of Reko to verify this (I just verified on my end). There is no perma-link to the most recent CI build, but if you navigate to Github's "Actions" tab:
![image](https://github.com/uxmal/reko/assets/10154465/017cdb74-64aa-4e2b-81a6-11a0eb1b4206)

then click on the topmost (most recent) successful run, and navigate to the bottom of the page, you'll find the artifacts from that CI run.

**Comment by juj** [comment]
Awesome!
