### ISSUE TITLE
Does reko support x86 linux binary?

### ISSUE THREAD

**Issue by Muqi-Zou** [uxmal/reko#1351]
I installed reko on Windows and it works perfectly for Windows binary.
However, reko cannot decompile my x86 Linux binaries. 
Do I need to specifically set something during the "Open Binary File" to support them?
Or is it just because reko does not currently support x86 Linux binaries?
If it is because reko does not currently support x86 Linux, could I ask why? 
Since I noticed reko supports Windows x86, it seems to me the main difference between their binaries is the issue of the calling convention, which is not that hard to be fixed.
[libevent_bufferevent_ratelim_o_O2.zip](https://github.com/user-attachments/files/16677841/libevent_bufferevent_ratelim_o_O2.zip)

**Comment by uxmal** [comment]
Thanks for reporting this issue. Reko does in fact support ELF binaries. However, it hasn't been thoroughly tested with relocatable object files (files that typically end in `.o`). The object files you provided are such `ET_REL` files. I've found a few issues that your binary files have exposed, and am working on a fix. I will put another comment here when the fix is completed.
