### ISSUE TITLE
What does "DPB" mean?

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#143]
There is **DPB** function in decompiled source code. What does it mean?

**Comment by uxmal** [comment]
The `DPB` function (http://www.outpost9.com/reference/jargon/jargon_19.html#TAG506) is a function in Common Lisp  that takes its name from a PDP-10 instruction, also called `DPB` (http://pdp10.nocrew.org/docs/instruction-set/Byte.html), which would **d**e**p**osit a **b**yte inside of a larger word. The fact that I'm aware of this instruction also reveals me as an *old-school* hacker :-)

For the m68k and other architectures, it models how a byte load is stored into an architectural register that is wider than a byte without modifying the remainder of the register.  For instance, the m68k instruction:
```
move.b (a5),d3
```
will be "lifted" to the RTL:
```
tmp = Mem0[a5:byte]     // load a byte from memory
d3 = DPB(d3, tmp, 0)    // deposit the byte at offset 0 of d3.
```
`DPB` is also used when dealing with aliased registers, like the x86 `ah` and `al` registers which are aliases of the `ax`, `eax` and `rax` registers.

The hope is that Reko should discover that all uses of `DPB` are followed by uses of casts or `SLICE`s, where `cast(<type>, <expr>)` is essentially the same as `SLICE(<expr>, <type>, 0)`. can be short-circuited and eventually eliminated. For instance, the m68k sequence:
```
move.b (a5),d3
move.b d3,(a2)
```
would be lifter to
```
tmp = Mem0[a5:byte]
d3 = DPB(d3, tmp, 0)
Mem0[a2:byte] = (byte) d3
```
Since the `(byte)` cast in the last instruction is discarding everything but the `tmp` part of d3 that was deposited, Reko should be able to infer that it can store `tmp` directly and thus:
```
tmp = Mem0[a5:byte]
d3 = DPB(d3, tmp, 0)
Mem0[a2:byte] = tmp
```
After this transformation, the `DPB` instruction is dead, and can be eliminated:
```
tmp = Mem0[a5:byte]
Mem0[a2:byte] = tmp
```
The Reko coalescer should then simplify this to 
```
Mem0[a2:byte] =  Mem0[a5:byte]
```
Most of the time, there should be few or no `DPB`'s emitted in the final code. If you can isolate a *small* fragment of machine code that still has `DPB`s and slices in it, please attach that fragment to this issue and I will investigate.

**Comment by uxmal** [comment]
@lab313ru: a recent commit should eliminate more unnecessary DPBs. There may more opportunities to eliminate DPBs, as well.

**Comment by uxmal** [comment]
I've added an edited version of this explanation to the wiki. Closing....

**Comment by lab313ru** [comment]
Could you give me a link to the wiki's page for DPB?

**Comment by uxmal** [comment]
The wiki explanation is shorter than the text above, but here it is (look at the bottom of the screen)
https://github.com/uxmal/reko/wiki/RTL

**Comment by lab313ru** [comment]
I can't still understand such lines:
﻿```
ui32 d1_153 = DPB(d1, a0->b0002, 0);
```
Because in your xplanation it was like this:
```
*d3* = DPB(*d3*, tmp, 0) 
```

**Comment by uxmal** [comment]
What you're seeing here is the instruction
```
move.b  2(a0), d1
```
first being lifted to
```
tmp = Mem[a0 + 2:byte]
d1 = DPB(d1, tmp, 0)
```
That is:
- read a byte into `tmp` 
- take that byte and overwrite the byte starting at bit offset 0 of `d1`:

Later, Reko converts the code to [SSA form](https://en.wikipedia.org/wiki/Static_single_assignment_form) which has the effect of introducing new identifier names each time a new value is computed. This helps greatly in code analysis:
```
tmp_1 = Mem0[a0 + 2:byte]
d1_2 = DPB(d1, tmp_1, 0)
```
Coalescing the two instructions yields
```
d1_2 = DPB(d1, Mem0[a0 + 2:byte], 0)
```
And type inference yields
```
d1_2 = DPB(d1, a0->b0002, 0)
