### ISSUE TITLE
Attempting to start requires an executable project?

### ISSUE THREAD

**Issue by LucasOne** [uxmal/reko#169]

**Comment by uxmal** [comment]
I'm not sure I understand the question. However, to build, you need to make sure you are building the Tools projects. In particular, the xslt.exe tool, which is part of the project, must be built first.

**Comment by uxmal** [comment]
If you want you can reach me at https://gitter.im/uxmal/reko the coming hour.

**Comment by uxmal** [comment]
OK, I saw your chat messages. Here's the basic scoop:

You could install the most recent official release, version 0.5.5.0, from https://github.com/uxmal/reko/releases, which would save you the effort of having to build reko yourself. If you're determined to get the most bleeding edge possible, you do need to learn how to use VStudio 2013 or later. Or, since I'm such a nice guy, I can make a bleeding-edge build for you!

I'd be glad to help you get started either way. Currently, I'm collaborating with @ptomin  on a relatively large change to the user interface that isn't ready for consumption yet, but I can make a 0.5.6.0 release from the master branch for you so you can benefit from the work we've been putting in the last two months.

**Comment by uxmal** [comment]
Closing this now, as I've been able to load the offered binary and scan the image.
