### ISSUE TITLE
Jump tables - ask dialog for amount of elements

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#213]
It would be great to add asking of jump table elements count for situations, if program cannot identify how much elements this jump table contains.

**Comment by uxmal** [comment]
Good suggestion! I'm thinking that reko should show a Warning, and if you click on the warning, you get the dialog where you specify the jump table bounds.

**Comment by uxmal** [comment]
Adding this link for reference: https://github.com/joelpx/plasma/wiki/jumptable

**Comment by uxmal** [comment]
I've made changes to the Reko GUI so that if you get a warning to the effect of "unable to resolve jump table", you can double click it and a dialog pops up, looking like this:

![reko](https://cloud.githubusercontent.com/assets/10154465/18783368/b5897f9c-818b-11e6-8c74-dc97e399206c.png)

Note that the feature is not yet complete, but is a prototype. If you have the time, play with the dialog and then add comments and suggestions here.
