### ISSUE TITLE
Reko disassembles negative int32 offsets incorrectly

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#252]
Disassembler shows `mov ecx,[ebp+FFFFFF60]` instead of `mov ecx,[ebp-000000A0]`
I have created unit tests to reproduce it in  	400faf1

**Comment by ptomin** [comment]
2f2e955 is proposed fix for this issue.

**Comment by ptomin** [comment]
Now expected output for HSC_HeuristicDisassembleProc and AsMem32 is incorrect. Is not it?

**Comment by uxmal** [comment]
This is is tricky, as the Intel addressing mode is ambiguous when the displacement is a full word. As far as I can tell in the Intel docs, the displacement is not to be interpreted as a signed word (unlike the 8-bit displacement, which *is* signed according to the documentation). This becomes especially tricky when encountering 16-bit x86 code like:
```
mov ax,[bp+FE00]
```
which could either be a reference to some value at offset -0100h from the `bp` register, which is common when using `bp` as a frame pointer, or a reference to some array element at address `ss:0FE00h` which is a perfectly valid thing to refer to if a data segment and a the stack segment overlap. 

It's hard for the disassembler to know which of the alternatives is the right one to choose for the 16-bit displacements, since a segment offset in the 0FE00h - 0FFFFh range is certainly very possible. For 32-bit displacement, the absolute addresses 0FFF00000h and higher are unlikely for userland code, but could be possible for some platforms. 

So how should the disassembler make the decision whether to treat the displacement of an x86 memory access as either a signed offset from a base register or unsigned segment offset? Naturally, reko knows what is what in later stages of the decompilaton; by then it can (usually) tell whether the base register is a pointer or an array index. For the disassembler, especially for 16-bit code, it's much harder to make a correct decision.

**Comment by ptomin** [comment]
> For 32-bit displacement, the absolute addresses 0FFF00000h and higher are unlikely for userland code

I suggest to modify disassembler so that it shows negative integers if the offset is more than `0FFF00000h`. This modification will be applied to `MemoryOperand.Write` method so it will not affect rewriter

**Comment by uxmal** [comment]
Good compromise. I will code this up in a few minutes.

**Comment by uxmal** [comment]
Pavel, look at the change and see if you agree with it. If you're dissatisfied, please reopen this issue with a comment.

**Comment by ptomin** [comment]
It works properly now. Thanks!
