### ISSUE TITLE
Some unhandled x86 instructions

### ISSUE THREAD

**Issue by xor2003** [uxmal/reko#304]
Decompiler looks like cannot handle x86 instructions like:
﻿test byte ptr [bx+3D],40
See project [https://cloud.mail.ru/public/2r7E/vja27S4je](https://cloud.mail.ru/public/2r7E/vja27S4je)
Several errors like:
0800:3118 Haven't handle this case yet.

**Comment by uxmal** [comment]
@xor2003: I'm not seeing any problem handling the `test` instruction per se. What I do see is exceptions with the text `Haven't handled this case yet` that you reported. Those are caused by reko mistakenly assuming that jump vectors will never be used from two or  more places in the executable, which is not true in your binary.

Another contributing issue is that you have, in the DCPROJ file, marked 0800:3118 as the address of a `uint16` location. However, that location is actually the start of a jump table, which should have the type `code seg0800::* []` (array of offsets into code in segment 0800; again a silent "thank-you" to Intel for their wonderfully conceived segment:offset addressing scheme that has brought such joy to programmers for decades).

**Comment by uxmal** [comment]
@xor2003: I will provide a fix for the first part (multiple users of jump vectors) but once I've commited it, you will have have to remove the reference to 0800:3118 (and possibly other locations as well) to get rid of the errors.

**Comment by uxmal** [comment]
Edited the subject to clarify the actual issue here. If you have:
```
0800:0123 jmp cs:[0124+bx]
```
and later
```
0800:51AA jmp cs:[0124+bx]
```
Reko crashes trying to overwrite the jump table twice.

**Comment by xor2003** [comment]
Thank you! The root cause here the program was written on assembler language originaly. So it was optimized by hand.

**Comment by uxmal** [comment]
This is closeable now, right?

**Comment by xor2003** [comment]
yes, closed
