### ISSUE TITLE
Ordinal global imports not supported.

### ISSUE THREAD

**Issue by eponymous4473** [uxmal/reko#315]
I was just trying to decompile something and got this message, followed by

Unable to resolve imported reference WS2_32.dll!Ordinal_115

This same form of message was repeated over and over, replacing 115 with 111, 227, etc and many more.

**Comment by uxmal** [comment]
You have to to give Reko a clue about what the ordinals of WS2_32.dll map to, otherwise it's impossible to know what to do with the ordinal. Fortunately, Reko understands Microsoft module defininition (`.def`) files, and has rudimentary support for the `.spec`  files used by the Wine project. Try adding the following metadata file to your .dcproject and see what happens:

https://github.com/wine-mirror/wine/blob/47cf3fe36d4f5a2f83c0d48ee763c256cd6010c5/dlls/ws2_32/ws2_32.spec

**Comment by uxmal** [comment]
Well, how embarrassing. Right now, the `reko.config` file has an incorrect line: where it reads:
```xml
      <Loader Extension="spec" Type="Reko.Environments.Windows.WinSpecFileLoader,Reko.Environments.Windows" />  <!-- Spec file used by Wine -->
```
it should read
```xml
      <Loader Extension="spec" Type="Reko.Environments.Windows.WineSpecFileLoader,Reko.Environments.Windows" />  <!-- Spec file used by Wine -->
```
(note the missing '`e`')

I will patch this in a little while. In the meantime go to the directory where the reko binaries are located and modify the `reko.config` file by adding the missing `e`.

**Comment by uxmal** [comment]
...and the `WineSpecFileLoader` has bugs that cause it to not handle the W2_32.spec file I linked to above. I should have a fix soon.

**Comment by uxmal** [comment]
OK, if you're able to build reko, try getting this latest commit and use the W2_32.spec file as metadata. If you run into issues, report them here.

**Comment by uxmal** [comment]
Closing this now; if you still have problems, create a new issue with the specifics of the issue.
