### ISSUE TITLE
Reko works incorrectly with floating return values

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#349]
Floating point return values of procedures seem to be incorrectly deserialised by `ProcedureDeserialiser`. See https://github.com/uxmal/reko/commit/a21846c367a2f9e9c1a6aba2c9773a82b5f44685#commitcomment-19666882

**Comment by uxmal** [comment]
There is a fundamental problem here that will take some reworking to resolve. The x86 rewriter tries to be clever by rewriting x87 instructions that refer to the FPU stack as rArg/rLoc instructions. The `X86State` class keeps track of how deep the FPU stack is in the member `FpuStackItems`, which models the x87 `TOP` register. The modelling fails when an indirect call is encountered by `X86Rewriter` because it has no way of knowing what the signature of the called function is this early in the decompilation process. Currently it silently assumes no FPU stack variables are pushed. In the fragment:
```asm
fld qword ptr [foo]
call dword ptr [function_returning_real32]
fstp qword ptr [bar]
```
the rewriter will not modify the FPU stack depth after the call, as it has no idea what the effects of `function_returning_real32` are. Therefore, Reko will incorrectly cause the  `fstp` to store in `bar` the value loaded from `bar`, instead of the value returned from the call:
```
rLoc1 = Mem0[foo:real32]
call Mem0[function_returning_real32:word32]
Mem1[bar:real32] = rLoc1    ; <= ERROR: should be rLoc2
```
Now all the rewritten FPU stack accesses after the indirect call are wrong.

To solve this we have to postpone the generation of `rLocX` FPU stack accesses until we have a way of introducing user type information into the decompilation process. Fortunately, The `analysis-developlent` branch is moving the SSA analysis much earlier in the decompilation process, which will make type information propagation much easier. Once that work is completed, we can leverage the work done for handling (regular) stack variables (Mem[fp +/ <const>] to deal with FPU variables as well. 

We start by making the x87 `TOP` register and the x87 FPU stack explicit when rewriting x87 instructions. At the entry of a procedure, where we today set `fp` equal to the stack pointer register, we can similarly set `TOP` equal to 0. The fragment above becomes:
```
TOP = 0 ; entry block
TOP = TOP - 1
x87Stack[TOP] = Mem0[foo:real32]
call Mem0[function_returning_real32:word32]
Mem0[bar:real32] = x87Stack[TOP]
TOP = TOP + 1
```
Indirect calls are hell nodes, and may trash the `TOP` register, so when doing the SSA rewrite we have to model the change made to `TOP`, just like how me model trashing the stack register. However, if the user has provided type information about `function_returning_real32`, we can use that to specify that the `FpuStackDelta` is 1. The resulting code, after SSA rewriting, would look like this:
```
TOP_1 = 0   ; entry block
TOP_2 = TOP_1 - 1
x87Stack[TOP_2] = Mem0[foo:real32]
call Mem0[function_returning_real32:word32]
    defs:x86Stack[TOP_2 - 1]
TOP_3 = TOP_2 - 1  ; generated based on signature of function_returning_real32
Mem0[bar:real32] = x87Stack[TOP_3] 
TOP_4 = TOP_3 + 1
``` 
Then value propagation will clean it up to:
```
TOP_1 = 0   ; entry block
TOP_2 = TOP_1 - 1
x87Stack[-1] = Mem0[foo:real32]
call Mem0[function_returning_real32:word32]
    defs: x86Stack[-2]
TOP_3 = -2  
Mem0[bar:real32] = x87Stack[-2] 
TOP_4 = -1
``` 
The second pass of SSA analysis can be adapted to handle expressions of the type `x87Stack[<const>]` just like it handles expressions `Mem0[fp +/- <const>]`. The result is:
```
TOP_1 = 0   ; entry block
TOP_2 = TOP_1 - 1
rLoc1 = Mem0[foo:real32]
call Mem0[function_returning_real32:word32]
    defs:rLoc2
TOP_3 = -2 
Mem0[bar:real32] = rLoc2
TOP_4 = -1
```
and after dead variable removal and coalescing:
```
rLoc1 = Mem0[foo:real32]
Mem1[bar:real32] = Mem0[function_returning_real32]()
```
which is the expected result.

I suggest waiting to fix this until `analysis-development` branch is complete, or at least stable enough to start implementing a fix. The steps required are:
- [ ] Introduce a new x86 register `TOP` and a memory identifier `x86Stack`
- [ ] Change the x86 rewriter to explicitly model the x87 FPU stack
- [ ] Make sure that TOP = 0 is injected in every x86 function.
- [ ] Adapt the new `SsaTransform` to deal with `x87Stack[<const>]` in a similar way it deals with `Mem[fp +/ <const>]

Comments?

**Comment by uxmal** [comment]
I'll start a dev branch tonight for this.

**Comment by uxmal** [comment]
Commit 318bcd206b445552cb48ec32d224a3470bd88285 is the root of the new `explicit-x87-stack` branch.

**Comment by ptomin** [comment]
Yes, It could wait until `analysis-development` branch is complete.
> Commit 318bcd2 is the root of the new explicit-x87-stack branch. 
Good start!

**Comment by uxmal** [comment]
OK, at this point, the `analysis-branch` has all the suggested steps above implemented. The remaining trick now is to make sure that Reko detects what part of the FPU stack has been modified, and uses that to buuild a procedure signature. That amounts to 9 unit tests failing, so I'm folding them into the `analyis-branch` *category* of disabled tests -- now at 69 failing tests. Once I get a properly working `TrashedRegisterFinder` for this, the bug can be closed.

**Comment by ptomin** [comment]
Nice!

**Comment by uxmal** [comment]
I beleive this old bug can be closed now.
