### ISSUE TITLE
C2Xml - Provide a way for specifying additional attributes

### ISSUE THREAD

**Issue by nemerle** [uxmal/reko#42]
It seems it would be advantageous to extend accepted ansi-c syntax by adding cpp++11's ```[[]]``` attributes
I have built a simple utility that can produce a list of augmented amiga library prototypes, it would be great if this information could be passed to reko.
As an example:
```cpp
//...............
[[reko_location(reg_D0)]] ULONG SetExcept([[reko_location(reg_D0)]] ULONG newSignals,[[reko_location(reg_D1)]] ULONG signalMask);
[[reko_location(reg_D0)]] APTR SetFunction([[reko_location(reg_A1)]] struct Library * library,[[reko_location(reg_A0.W)]] LONG funcOffset,[[reko_location(reg_D0)]] APTR funcEntry);
[[reko_location(reg_D0)]] struct Interrupt * SetIntVector([[reko_partial_location(reg_D0,"0:4")]] ULONG intNumber,[[reko_location(reg_A1)]]  struct Interrupt * interrupt);
[[reko_location(reg_D0)]] ULONG SetSignal([[reko_location(reg_D0)]] ULONG newSignals,[[reko_location(reg_D1)]] ULONG signalMask);
[[reko_location(reg_D0)]] ULONG SetSR([[reko_location(reg_D0)]] ULONG newSR,[[reko_location(reg_D1)]]  ULONG mask);
[[reko_partial_location(reg_D0,"0:8")]] BYTE SetTaskPri([[reko_location(reg_A1)]] struct Task * task,[[reko_partial_location(reg_D0,"0:8")]] LONG priority);
//...............
```

**Comment by uxmal** [comment]
I prefer the syntax
```
[[reko::register("D0",0,8)]]
[[reko::register("A1")]]
[[reko::stack]]
```
using namespaces to qualify the attribute and avoiding having to parse a string "0:8" when looking at byte slices.

It seems to me that specifying a byte slice (0,8) is redundant in 
```C
[[reko_partial_location(reg_D0,"0:8")]] BYTE SetTaskPri(...
```
since the function declaration already specifies the return type. Agree?

I should be able to write an implementation of this in a couple of days. Just want to make sure that we're in agreement on what the syntax is.

**Comment by nemerle** [comment]
As for syntax - yes, I realize that parametrization for other machines/environments will be much easier if register names are not hard-coded into attributes :smile: 

As for redundant slice..
* It's from auto-transformed code - might actually be redundant
* _unlikely_ The function actually  preserves the higher bits of D0 ?

when the support for this kind of attributes is 'in' we might steal boomerang's idea of allowing specifying full stack locations and have something like:
```
[[reko:memory("SP",-4)]]
```

**Comment by nemerle** [comment]
I've started implementing this on c2xml_attributes branch

**Comment by uxmal** [comment]
The token `register` is a reserved keyword in C/C++. Please switch to `reg`.

**Comment by nemerle** [comment]
Replaced 'register' with 'reg' in 52b375172c870f7e74cbd5f3bf0c62cf2b34ba2a

**Comment by uxmal** [comment]
I just checked in the C parser portion, following quite closely the C++11 spec section 7.6. In particular, the spec indicates that between `[[reko::reg(` and `)]]`, any list of **balanced tokens** is allowed. This means that the new class `CAttribute` contains a list of tokens, and it is the job of the compiler/reko to interpret those tokens correctly. Right now, the interpretation is easy:
`[[reko::reg( <StringConstant> )]]` for register declarations
`[[reko::mem( <StringConstant>  <Comma> (<Minus>) <Integer> )` for memory declarations

**Comment by uxmal** [comment]
Feature implemented in `master`. Now all we have to do is make reko recognize the services as A6-based. That's a different issue <g>. Please verify that you can build and run any tests you think appropriate, then close.

**Comment by nemerle** [comment]
Awesome :smile:

I've fixed a few problems in the exec_functions header, but there is one feature missing -> handling the bit selection in reg attribute. I could remove the bit selection from the header, but that will remove some of the data decompilation might find useful ? Or I might extended attr handling to preserve the bit-range in Register_v1 class ?
```c
void AddIntServer([[reko::reg("D0",0,4)]] ULONG intNum,[[reko::reg("A1")]] struct Interrupt * interrupt);
```

**Comment by uxmal** [comment]
Leave the bits in the file; the current implementation of `[[reko::reg]]` will just ignore them. Bit slice handling is should be handled generically by `ApplicationBuilder`.

Reko has an internal issue, which is the representation of data in registers which may be smaller than the register size itself. On the x86 we are lucky because the processor has aliases for the smaller pieces of the register (rax, eax, ax, al) but many other architectures like m68k and PowerPC don't. I expect I will have to take a look at `ApplicationBuilder` and its related classes to see what can be done.

In the meantime, can we consider this issue resolved? Attributes can now be specified, and we can add more, like [[noreturn]], which is a standard attribute that indicates that procedures don't return (think `exit(int n)`).

**Comment by nemerle** [comment]
This fails
```
void f([[reko::reg("D0",0,4)]] int intNum);
```
with:
```
System.FormatException: [[reko::reg]] attribute expects a register name.
```

**Comment by uxmal** [comment]
Fixed now.

**Comment by nemerle** [comment]
The file is parsed correctly now
