### ISSUE TITLE
Migration to C# 7.0, .NET 4.7 and NUnit 3.0

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#499]
In issue #498, @chostelet asks:

> Do you have any plan to migrate to C# 7.0 (multiple syntax simplifications), .NET 4.7 and NUnit 3 ? .NET 4.7 should be straigthforward.

I would love to migrate to C# 7.0. The new syntax for inline declarations in particular would be very nice as I see the code littered with statements like
```C#
var id = expr as Identifier;
if (id != null) { // stuff
}
```
and 
```C#
Identifier id;
if (dict.TryGetValue(key, out id)) { // stuff
}
```
which would be cleaner with the new syntax C# 7.0. Before I can do that, however, I have to make sure that the Mono compiler being used by non-Windows users has been upgraded to that new language standard. 

I'm not sure what benefit using .NET 4.7 would have on the current setting .NET 4.5. The Reko project doesn't depend on a lot of cutting-edge features but perhaps you have identified some such features? What would be the advantage?

Moving to NUnit 3.0 would be nice. There are in the current day  over 4600 unit tests in the solution. If I could find a volunteer to move those tests over and make them all pass, that would be fantastic. Perhaps you @chostelet feel brave enough to create a `NUnit-3.0` branch and perform this work? :-)

**Comment by chostelet** [comment]
Salut John  (tu parles/lis/écris le français ??)

 

*Don’t know if following needs to be kept as private mail or can be put in the issue ticket.*

 

Let me give you some background on the context why I’m sending you so many issue notifications :)

 

I’m attempting since some months, to design a “clever” disassembler for some Microchip PIC microcontrollers.

I’m a bit aware of the various steps of decompilation (literature, raw disassembler) but absolutely not an expert.

 

And I found your project which is really a jewel that I’d like either to use and extend and/or get inspiration from.

It is the very first example I’ve seen of an open-source software which implement CFA, DFA, etc… for real, in C# and, even more, with a GUI under Windows!!

A dream :)

 

Then I got a snapshot (master-zip) of it and imported it in Visual Studio 2017. I do not know GitHub well enough and I did not want to start a clone project.

 

As a first step, I’ve already “migrated” to .NET 4.7 without a warning (Build). Please note that I’ve not executing the tests yet (thus my question on NUnit 3.0 that I’m using for other projects).

The only advantage I’m seen up to now, is to keep in sync with .NET’s evolution (and avoid future disruption).

 

As a second step I’ve started to scrutinize thoroughly the source (review it) to try to understand what you’ve done and how. Documentation is helpful, but is really scarce.

 

At the same time I’m browsing the source, I’m rewriting it to the C# 7.0 syntax to help me understand better.

Inline declaration of variable is one of the syntactic transformation as you already mentioned.

Another one I found valuable is the pattern matching on a switch statement. There are many occurrences in your modules for this transformation why really illuminate the source (e.g. Operand Rewriters);

 

…

switch (operand)

{

    case RegisterOperand reg:

        {

            Expression r = _binder.EnsureRegister(reg.Register);

            if (DataWidth != null && DataWidth.Size != reg.Width.Size)

                r = _m.Cast(DataWidth, r);

            return r;

        }

    case M68kImmediateOperand imm:

        {

            if (imm.Width.Domain == Domain.Real)

                return imm.Constant.CloneExpression();

            if (DataWidth != null && DataWidth.BitSize > imm.Width.BitSize)

                return Constant.Create(DataWidth, imm.Constant.ToInt64());

            else

                return Constant.Create(imm.Width, imm.Constant.ToUInt32());

        }

    case MemoryOperand mem:

        return _rewriteMemoryAccess(mem, DataWidth, addrInstr);

… 

 

I’ve too used the short notation “=>” for some properties and methods:

 

public Expression RewriteDst(MachineOperand operand, Address addrInstr, Expression src, Func<Expression, Expression, Expression> opGen)

    => RewriteDst(operand, addrInstr, DataWidth, src, opGen);

Something more, but which you may not appreciate :), is modifying the name of most of the private fields and properties to start with an underscore and a lowercase letter.

 

public class OperandRewriter

{

    private M68kArchitecture _arch;

    private RtlEmitter _m;

    private IStorageBinder _binder;

This helps recognizing those local things and permits to remove the redundant ‘this.’.

 

I’m also making sure all interface definitions start with an I (uppercase “i”) to avoid an annoying naming rule violation warning (code IDE1006) in VS2017.

 

Of course, all of this is done by Refactoring on the whole solution, source after source, file after file.

A tedious work, but this will probably help me better understand.

Last, at the same occasion I’m adding some comments (xml documentation) to the parts I feel I understand well-enough.

 

I've not looked in details to the tests yet. I’ll do later.

 

I’m not against being one of the volunteers, but not before 2018. As my end of year will be a bit too busy.

 

Regard / Cordialement

 

--

Christian HOSTELET - Grenoble

 

De : John Källén [mailto:notifications@github.com] 
Envoyé : samedi 18 novembre 2017 14:00
À : uxmal/reko <reko@noreply.github.com>
Cc : chostelet <christian.hostelet@free.fr>; Mention <mention@noreply.github.com>
Objet : [uxmal/reko] Migration to C# 7.0, .NET 4.7 and NUnit 3.0 (#499)

 

In issue  <https://github.com/uxmal/reko/issues/498> #498,  <https://github.com/chostelet> @chostelet asks:

Do you have any plan to migrate to C# 7.0 (multiple syntax simplifications), .NET 4.7 and NUnit 3 ? .NET 4.7 should be straigthforward.

I would love to migrate to C# 7.0. The new syntax for inline declarations in particular would be very nice as I see the code littered with statements like

var id = expr as Identifier;
if (id != null) { // stuff
}

and

Identifier id;
if (dict.TryGetValue(key, out id)) { // stuff
}

which would be cleaner with the new syntax C# 7.0. Before I can do that, however, I have to make sure that the Mono compiler being used by non-Windows users has been upgraded to that new language standard.

I'm not sure what benefit using .NET 4.7 would have on the current setting .NET 4.5. The Reko project doesn't depend on a lot of cutting-edge features but perhaps you have identified some such features? What would be the advantage?

Moving to NUnit 3.0 would be nice. There are in the current day over 4600 unit tests in the solution. If I could find a volunteer to move those tests over and make them all pass, that would be fantastic. Perhaps you  <https://github.com/chostelet> @chostelet feel brave enough to create a NUnit-3.0 branch and perform this work? :-)

**Comment by chostelet** [comment]
Me again,
For curiosity, I started to used NUnit 3.9 (current version) for the tests.
After correcting some **[Ignore]** into **[Ignore("")]** (reason string being mandatory with NUnit 3.0) as well as replacing the **[ExpectedException]** with equivalent **Assert.Throws** I got 4283 tests being passed, 86 being skipped and 190 failing. Not so bad. Of those failing, almost all them are due to multi-line strings comparison where the difference is only the line termination (getting "\r\n" instead of "\n").
Effectively, StringBuilder.AppendLine() uses the default Environment.NewLine which is "\r\n" on Windows systems. But the source file of tests are written using only "\n" as line terminator (Linux?).
In fact, as soon as I got the source of a test into a text editor able to transform Linux "\n" to Windows "\r\n", the test succeed...

Maybe we should have to resort to String.Join() for those text strings to get a consistent line termination.
Regards

**Comment by chostelet** [comment]
Once more,
Same kind of issue with the "tabification" (TAB , \t).
Those issues come from the @"" literal strings which highly depends on how the file is saved under VS and if the user decides to select 'Tabify' or 'Untabify' as asked by VS when opening the file.

To be continued

**Comment by uxmal** [comment]
Certes, je parle et écris le français, même si cela fait longtemps que je ne l'ai pas fait régulièrement. Malheureusement, je n'ai pas beaucoup de connaissances françaises là où je vis, alors je perds lentement mon vocabulaire - en particulier dans le domaine de l'informatique. Ainsi, je passe à l'anglais maintenant.

Firstly, welcome! I'm always gratified when I hear from people who are interested in Reko, and I'm glad that the project can help them in their reverse engineering endeavors. I especially appreciate constructive feedback from users as it helps guide development. I also have a vested interest in involving people in actively contributing to the project, be it by reporting issues or by submitting pull requests using Git. For a long time it's been the work of a single person, but with the migration to GitHub it's received a lot of great submissions by others for which I'm very grateful.

So you touch upon a number of issues about the codebase. Let's see if I can address them. Bear in mind that the codebase has a long history. I started working on the first piece of Reko (at the time called "grovel") in 1999. At that time I was reversing an MS-DOS binary that was written in assembler language. It had some constructs that the disassembler I was using couldn't cope with, so I wrote my own, in C++ (dialect of 1998). You can still witness the relics of this code in `X86Disassembler`. In particular, notice how many of the static members (e.g. `s_aOpRec`) contain a `s_` suffix to indicate that they are static / global variables. Another relic of this stage is the occurence of tabs in the source code: Visual C++ prefers using literal tabs even to this day.

At a later time (I forget now when exactly, but c:a 2002-2003) I ported the project to C# 1.x. No generics was a pain, and some of the older parts of Reko reflect this design restriction. When C# 2 came out I gratefully started to use the new generics feature -- where it made sense. When C# 3 was available, I started using LinQ -- where it made sense. However, in general I refrain from wholesale rewrites unless I deem they yield value: (measurably) faster code, or (substantial) code cleanliness. I want to focus on functionality rather than jumping on the latest features -- except when it makes sense to do so. I also am constrained by the rate at which development environments and users adopt new features. I don't want to exclude users who are using reasonably old toolsets from participating. Right now, I want to make sure that VS2015 users can still work with the project. This unfortunately rules out C# 7 features at the moment, even though they are highly desirable. Given a year or so, Reko will likely move to C# 7, in the sense that PR's using C# 7 will be accepted. I don't expect a total rewrite of the project, but rather if a developer is modifying a class anyway they might go in and update older code

I haven't published any coding guidelines for the Reko project, but it seems appropriate now that there are many people tinkering with it that I come up with such a document, to avoid "source control wars". I tend to follow the style of the Microsoft.NET back in the day, where underscored prefixes like `m_`, `s_` and `_` are avoided in preference to using "this" to disambiguate in the cases where it is needed. Methods should be small enough that it should be obvious whether a variable reference is a member field or a local variable. 

As for the CRLF issue: since you downloaded the Reko solution as a zip archive rather than using git, you received all files using Unix newlines. When you then run unit tests they will generate CRLFs with the subsequent false negatives in the unit tests. There are two approaches to solve this. 

The most expedient is naturally to use git or a suitable Windows Git client (I personally work both with the integrated git client in VS2015 and TortoiseGit explorer extension, which works great). You will then immediately benefit from automatic CRLF translation. It will also make your life easier when contributing your changes.

A long-term solution which requires a lot more effort is to adapt the affected unit tests to circumvent such issues. You'll notice that some tests use a readonly literal `nl = Environment.Newline`, but this become tedious in large segments of code. Using @literal strings works well enough; viz. all unit tests run fine both on Windows and Unix _if_ you used git with its autocrlf feature to deal with the CRLF issue. However, it would be nice to adapt the unit tests to normalize line endings before performing comparisons. That is, before comparing strings, call some `CrlfToNewline(string s)` method to normalize. This would take some dedication and effort to bring to bear: textual comparison are used in the great majority of the unit tests that verify instruction rewriting.

As for @literal strings, if they do contain literal tabs, the C# editor typically respects this. I do admit that requiring literal tabs in the unit tests can be tedious. It would require changing the line in `Block.WriteStatements()` to `f.UseTabs = false` and then adjust a large number of tests to conform. 

Finally, as for sparsity of comments, please don't be shy in pointing out specific places where you think there should more comments. I'm more than happy to document the code, it's just that there is so much of it!

**Comment by chostelet** [comment]
Bonjour John,

Ton français me semble parfait même si tu penses en avoir perdu la pratique.
Je passe à l'anglais également dans le cas où cette discussion pourrait intéresser d'autres contributeurs.

Thank you for describing me the history of the genesis of Reko. A really big project!
I understand the various constraints and mitigations you've to take care of.

To alleviate the problem of the CRLF and restart on a better basis, I've installed the GitHub extension in my VS2017 and created a cloned repository of Reko on my PC. I then refrained to "untabify" the sources :-)
After adding some additional VS features I'm usually not using (WiX, ASP.NET) I was able to build the whole solution without a glitch. Keeping .NET 4.5 as the framework.
I then ran the UnitTests "as-is" (didn't touch any of the files) with the result of 87 tests being Skipped and the rest (4512) being Passed.
I suppose this is the result one should expect.

I then changed the test framework to NUnit3.9 (thru NuGet package manager), re-built the solution.
I got some errors messages related to the breaking changes as documented on NUnit.org

[Ignore] - missing description string; I added empty strings (not knowing the reason of the ignore).
[TestFixtureSetUpAttribute] replaced by [OneTimeSetupAttribute]
[ExpectedException(typeof (...)] by adding an Assert.Throws<...>() around the throwing statement.

Rebuilding, re-running...
The result is: still 87 tests skipped, 5 failing, the rest (4507) being Passed.

The 5 failing are:

`1) RwFtol
2) RwGlobalHandle
3) RwLoopGetDC
4) RwLoopMalloc
5) RwMallocFree`

All of them get a string difference which is neither the tabs nor CRLF.
The resulting strings differ on the readable content.
For example, for the 'RwFtol' the message is:

_**Test Name:	RwFtol
Test FullName:	Reko.UnitTests.Arch.Intel.Rewrite32.RwFtol
Test Source:	L:\Software\Visual Studio\Projects\Reko\Reko_NUnit3\src\UnitTests\Arch\Intel\Rewrite32.cs : line 98
Test Outcome:	Failed
Test Duration:	0:00:00,045

Result StackTrace:	
à Reko.UnitTests.FileUnitTester.CompareFiles(StreamReader expected, StreamReader test) dans L:\Software\Visual Studio\Projects\Reko\Reko_NUnit3\src\UnitTests\FileUnitTester.cs:ligne 104
   à Reko.UnitTests.FileUnitTester.AssertFilesEqual() dans L:\Software\Visual Studio\Projects\Reko\Reko_NUnit3\src\UnitTests\FileUnitTester.cs:ligne 122
   à Reko.UnitTests.Arch.Intel.Rewrite32.RunTest(String sourceFile, String outputFile) dans L:\Software\Visual Studio\Projects\Reko\Reko_NUnit3\src\UnitTests\Arch\Intel\Rewrite32.cs:ligne 186
   à Reko.UnitTests.Arch.Intel.Rewrite32.RwFtol() dans L:\Software\Visual Studio\Projects\Reko\Reko_NUnit3\src\UnitTests\Arch\Intel\Rewrite32.cs:ligne 99
Result Message:	
File differs on line 19
  Expected string length 19 but was 32. Strings differ at index 1.
  Expected: "\teax = _ftol(rLoc2)"
  But was:  "\tcall ftol (retsize: 4; FPU: 2;)"
  -------------^**_

Interesting to see that *only* changing the NUnit version, is changing the result. 
Migration of the 3 directives seems unrelated to those 5 failing tests.
And all 5 of them are related to 'Fragments/import32'

I've attached the result text file for RwFtol (the '.exp' already being on GitHub).

[RwFtol.txt](https://github.com/uxmal/reko/files/1485702/RwFtol.txt)

Before trying to dig further into, maybe you've a clue (and enough time to spare)

Regards.

**Comment by chostelet** [comment]
Just as a temporary follow-up.

I switched back to NUnit 2.6 (using NuGet), modified back only the [Setup] to [TestFixtureSetUp] directive (sources 'DeadConditionFlagsFinderTests.cs' and 'OperandRewriterReadModeTests.cs'), leaving Ignore and Assert.Throws<...> (which is known to 2.6), rebuilt the solution and ran.
All tests Passed or Skipped as before.
It appears, the offending tests are not able to retrieve the information contained in 'msvcrtl.xml' definition file. The file is considered as not existing; something around retrieving its path.

I'm still investigating.

Regards

**Comment by smx-smx** [comment]
> however, I have to make sure that the Mono compiler being used by non-Windows users has been upgraded to that new language standard.

According to the Mono website (and monodevelop, i just checked it), they switched to the Roslyn compiler (csc.exe). As such, .NET 4.7 is supported

**Comment by chostelet** [comment]
Good news.

**Comment by chostelet** [comment]
Hello,

What I found up to now.

The issue arises in 'LoadMetadataIntoLibrary' (in ITypeLibraryLoaderService.cs') when trying to get the absolute path to the library file via a call to 'cfgSvc.GetInstallationRelativePath(tlElement.Name); '.
In both NUnit environments the path returned is not absolute but still relative (e.g. "msvcrt.xml").
The difference being that when running tests under NUnit 2.6, the current directory and working directory are same (the '...\bin\Debug' directory) while at the same time running under NUnit 3, the working directory is '...\Common7\IDE' (the Visual Studio working dir).

Just to be clear, those paths are retrieved as follow...
working directory = Directory.GetCurrentDirectory()  [System.IO]
running directory = Path.GetDirectoryName(GetType().Assembly.Location) [System.IO, System.Reflection]

Going further is difficult, because I'm unable to hit a breakpoint in the implementation of GetInstallationRelativePath() [file 'RekoConfigurationService.cs'] which is probably called thru Rhino Mocks library. And it looks like the function 'Path.IsPathRooted' is not behaving as expected in the NUnit context.
Should check further. To be continued.

**Comment by uxmal** [comment]
The fact that the unit tests are failing depending on the disk layout stronly suggests that they are not "unit  tests" in the strict sense. I will look at fixing these so that they stop depending on paths and hope to have something for you within a few days.

**Comment by chostelet** [comment]
As a temporary patch, I've added a SetCurrentDirectory (to the execution directory) in the [Setup] of 'Rewrite32.cs' test fixture, and all tests - 4512 - passed (but those ignored - 87) with NUnit 3.9.
What is still very strange to me is that the call to 'cfgSvc.GetInstallationRelativePath(tlElement.Name)' in 'ITypeLibraryLoaderService.cs line #61) which I guess is supposed to return the absolute path, is not when running the tests whenever NUnit2 or 3.

Now, I still see a difference in the fact there are no messages (Output panel of VS) during the execution of the tests under NUnit3 contrary to Unit2.
Shall investigate further.
.

**Comment by uxmal** [comment]
Christian, I've modified the "unit" test to generate correct paths for the metadata files. IF you pull commit a27c6d0 you should be in the clear.

**Comment by uxmal** [comment]
Well, I spoke too soon.  AppVeyor is complaining about my commit. Investigating.

**Comment by chostelet** [comment]
John,
I've done the modifications and that's correct. Tests passed.

Still remain the question on the Debug outputs.

PS: I was not able to see these modifications (a27c6d0) in my Visual Studio so performed the changes manually (checking 2 times).
Probably the mistake is between my chair and my keyboard (new to GitHub).

**Comment by uxmal** [comment]
Re: Debug outputs, are you building the Debug or the Release version? Release version will suppress any output generated by `Debug.Print` and `Debug.Write{Line}`. 

Also, be aware of the channel https://gitter.im/uxmal/reko if you want more interactive communication.

**Comment by chostelet** [comment]
I'm building all projects in Debug/Any CPU mode and the DEBUG and TRACE constants are activated (Project properties -> Build). I hope (expect) that switching from NUnit2 to NUnit3 does not change the setup of the projects (!).

OK for gitter.
You're giving great support!

**Comment by uxmal** [comment]
Commit d8dd5e4 finally fixes this. You shouldn't have to use `SetCurrentDirectory` anymore.

**Comment by chostelet** [comment]
Merci John,

 

Due to the fact I’m learning GitHub (yes, this is not a joke!) I initially *cloned* your project but refrained to commit anything.

Now I’ve *forked* it, shall perform again the NUnit migration and will let you know.

This will make me more comfortable not to put garbage in your project :)

 

Cordialement

--

Christian HOSTELET - Grenoble

 

De : John Källén [mailto:notifications@github.com] 
Envoyé : lundi 20 novembre 2017 15:56
À : uxmal/reko <reko@noreply.github.com>
Cc : chostelet <christian.hostelet@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [uxmal/reko] Migration to C# 7.0, .NET 4.7 and NUnit 3.0 (#499)

 

Commit  <https://github.com/uxmal/reko/commit/d8dd5e46ea5759c19e2abf51be2e73eec3313436> d8dd5e4 finally fixes this. You shouldn't have to use SetCurrentDirectory anymore.

**Comment by chostelet** [comment]
I got a fork from your latest commit, executed tests with NUnit 2.6.3 - no issue - then NUnit 3.9.0 after amending the [Ignore], [Expected...] and [TestFixtureSetup] - no issue but no debug outputs.
To verify this was not specific to your project, created a tiny WinForm project, having some Debug.Print to check - same behaviour. NUint 3.9.0 is not showing debug prints. 
Shall investigate.

**Comment by chostelet** [comment]
OK,

After digging in NUnit 3 issues, it looks like that not having the test application's output (Debug.Print, Debug.Write,Trace) is a design decision. A "feature".
Someone suggested a workaround like adding:

`        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            Trace.Listeners.Add(new ConsoleTraceListener());
        }
`

in each TestFixture class that are supposed to produce some console output.

However the various output for each test will not be sent and concatenated into the Output window, but will be made available in each test's result window thru an "Output" button/link.

Don't know if that would be acceptable.

**Comment by uxmal** [comment]
That's really regrettable from the NUnit 3 team. I frequently rely on having the unified output in the debug window. This is not the right place to critique their design choices, but it does make me very hesitant to move forward with NUnit 3. 

As I feared, for the time being, the Reko project will have to remain on NUnit 2.x, .NET Framework 4.5 and C# 6 due to backwards compatibility issues. At best, what you could do is create a branch in your forked repository where you could maintain the changes you've made while waiting for the time when I think we can go ahead and move forward into the new runtime + compiler.

I'm sorry to see you having put down so much effort only to run into this wall. I hope you don't get discouraged but instead see this as a learning experience; you've gotten more acquainted with Git and the Reko codebase. My hope is that within a year or so, most of the active developers will have migrated to .NET 4.7 and can build with C# 7. At that point we can merge your changes. I'm going to leave this issue open to track the developments on this front. I encourage other people interested in Reko to chime in on this topic as well.

**Comment by chostelet** [comment]
John,

I fully understand your position and do not wish to force you in a way which is not one you would support and feel comfortable with. And I'm not discouraged :-) At all.
I shall do as you suggest (fork + branch) to migrate to NUnit 3 and .NET 4.7, and probably leaving for the time-being the C# 7.0 features.
And keep deciphering all the goodies that are there, and give appropriate feedback.
And maybe, at some time in the future, I'll feel confident to propose (build) the addition of a new processor  architecture (Microchip PIC16 / PIC18).

**Comment by uxmal** [comment]
After commit 872542d65fddbdb3dd096242814752d75073a300 we are now at C# 7.0 and .NET Framework 4.7. As for NUnit 3, I wish to experiment with it before I start converting. Watch this space.

**Comment by chostelet** [comment]
Good. Shall transition me too after resyncing with master.

**Comment by uxmal** [comment]
Well, long after the fact, it appears it's all working. Thanks to @chostelet  for the NUnit 3 port!

**Comment by chostelet** [comment]
Hi John

 

Thanks for the credit.  Should come back later. PIC16 and PIC18 decompilation is still not satisfactory.

 

Bien cordialement

--

Christian HOSTELET - Grenoble

 

De : John Källén <notifications@github.com> 
Envoyé : jeudi 4 avril 2019 01:16
À : uxmal/reko <reko@noreply.github.com>
Cc : Christian Hostelet <christian.hostelet@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [uxmal/reko] Migration to C# 7.0, .NET 4.7 and NUnit 3.0 (#499)

 

Well, long after the fact, it appears it's all working. Thanks to @chostelet <https://github.com/chostelet>  for the NUnit 3 port!
