### ISSUE TITLE
Question on RTL code generated for M68K jumptable

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#500]
Just a couple of questions on the RTL code generated for the sample below
(C)-> is code
(RTL)-> is RTL

﻿(C)-> 00106690 0C 81 00 00 00 28 cmpi.l#$00000028,d1
(RTL)->﻿l00106690:
(RTL)->    v80 = d1 - 0x28
(RTL)->    CVZN = cond(v80)

(C)-> 00106696 6E 00 05 CE bgt$00106C66
(RTL)->    branch Test(GT,VZN) l00106C66

(C)-> 0010669A D2 81 add.ld1,d1
(RTL)->l0010669A:
(RTL)->    d1 = d1 + d1
(RTL)->    CVZNX = cond(d1)

(C)-> 0010669C 32 3B 18 06 move.w(06,pc,d1),d1
(RTL)->    v82 = Mem0[0x001066A4 + d1:word16]
(RTL)->    d1 = DPB(d1, v82, 0)
(RTL)->    CVZN = cond(v82)
How is the size of the memory read for v82 defined?
For the DPB generated above does that work for word16 as well as byte?

(C)-> 001066A0 4E FB 10 00 jmp.l(pc,d1)
(RTL)->    call 0x001066A2 + (int32) ((int16) d1) (retsize: 4;)
(RTL)->    return
Why is the jump converted to a Call and Return?

**Comment by uxmal** [comment]
> (RTL)-> v82 = Mem0[0x001066A4 + d1:word16]
> How is the size of the memory read for v82 defined?
The `word16` inside the `Mem0[...]` indicates a 16-bit result. `DPB` should be read as "deposit bits".

> (RTL)-> call 0x001066A2 + (int32) ((int16) d1) (retsize: 4;)
> (RTL)-> return
> Why is the jump converted to a Call and Return?

Since we can't tell where the jump is going -- as the current implementation of indirect jump resolution is weak -- we have to punt and assume the worst. We still have to generate some form of high-level language. In C, there is no way to write 
`goto table[index];`
but there is a way to accomplish the same thing by writing:
`(table[index])(); return;`
What Reko does is basically the reverse of a "tail-call optimization".
