### ISSUE TITLE
Editing procedures

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#506]
After deselecting "Decompile body of this procedure" and selecting it again, the procedure name stays pink. I have tried restarting within the same session.

Also wondering what the format is for the procedure signature

**Comment by uxmal** [comment]
I think you are referring to the "Edit procedure" dialog:
![image](https://user-images.githubusercontent.com/10154465/33277588-4d978558-d399-11e7-86ea-367286b11fd3.png)
The dialog is a little confusing: the idea is that you either _just_ change the name in the `Name` textbox or you enter the signature + name as if it were a C function. For instance, in the screenshot above you could type `int main(int argc, char ** argv)` and Reko should accept it as the new signature.

The format is simply C-style with the following additions. If the signature of the procedure violates the "standard calling convention" for a particular platform, you can override it. If the signature conforms to 
an alternate calling convention, you can specify it like this:
```C
bool __stdapi DestroyWindow(HWND hwnd);
char * __fastcall my_string_routine(char * a, char * b);
```
If there is no corresponding calling convention -- typically because values are being passed or returned in non-ABI registers -- you can specify these explicitly using the 
attribute syntax used in C++:
```c++
[[reko::returns(register,"d3")]] int add_two_numbers(
    [[reko::arg(register,"d2")]] int d2,
    [[reko::arg(register,"d4")]] int d4);
```
The signature above tells Reko that the parameters are being passed in registers `d2` and `d4` respectively, and the return value is in register `d3`.

**Comment by gbody** [comment]
@uxmal  with the register style syntax are the types limited to int, long only. I tried boolean but it wouldn't accept it as being valid

**Comment by uxmal** [comment]
Could you enter the exact syntax you tried? It's possible the C parser doesn't understand `bool` or `_Bool` yet. `boolean` is Pascal.

**Comment by gbody** [comment]
@uxmal I have tried bool, _bool & boolean
[[reko::returns(register,"d0")]] bool _DATAINIT(
    [[reko::arg(register,"a5")]] long a5);

**Comment by uxmal** [comment]
I just pushed a fix that should be able to handle `bool`.
