### ISSUE TITLE
printf detection - What do I miss?

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#518]
I'm using 0.7.2.0

When I decompile a subject which uses printf reko doesn't discover the format string or the arguments. This makes it hard to compare or find errors in the decompiled output.

Maybe reko supports this but I didn't have it installed correct/used correct. Or some signature files are missing.

See for example https://github.com/rfalke/decompiler-subjects/tree/master/from_boomerang/hello/ia32_elf_by_boomerang  and then "by_reko.c". I get the some output "printf@@GLIBC_2.0();" in main() when I run it interactively on a windows pc.

**Comment by uxmal** [comment]
It could be the @@GLIBC_2.0 suffix that may be throwing reko off the rails. I know that Boomerang makes an effort to trim off that suffix before proceeding with ELF symbols. I would have to learn a little about what the purpose of that suffix is, but it's easy enough to trim such suffixes and proceed. 

Out of curiosity, what does holdec do with such symbols?

**Comment by uxmal** [comment]
Looking at the ELF binary, the symbol for `printf` looks OK. No weird suffix.

Reko keeps a configuration file with "characteristics". These characteristics specify extra-linguistic information that cannot be conveyed in C/C++. For `printf`, we specify the name of the Reko class that knows how to interpret the format string. It looks as if Reko is not finding the characteristics for `printf`, so you get no "Hello world". I will see if this can be fixed with a simple edit, or whether it requires a code change.

**Comment by rfalke** [comment]
Regarding the symbols: the binary contains two symbols with the same value. One with and one without the version suffix. In such case holdec just chooses the one without the suffix.

So maybe I have some old version of the file?

**Comment by uxmal** [comment]
Turns out that we never were associating characteristics with imported procedures on ELF binaries! The fix above makes your sample work. Thanks for reporting this, Raimar.

**Comment by rfalke** [comment]
Works as expected.
