### ISSUE TITLE
Detected char pointer instead of int

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#544]
Version: 0.7.2.0-f51c658d81
File: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/signed_unsigned_comparsion/ia32_elf

Output:
```
void f( tArg00, char * ptrArg04, char * dwArg08)
{
	if (ptrArg04 <= (char *) 0x07)
		printf("%d signed in range\n", ptrArg04);
	if (dwArg08 > (char *) 0x07)
		;
	else
		printf("%d unsigned in range\n", tArg00);
}
```

Source:
```
void f(int s, unsigned u)
{
        if (s >= 2 && s <= 7) {
                printf("%d signed in range\n", s);
        }
        if (u >= 2 && u <= 7) {
                printf("%d unsigned in range\n", u);
        }
}
```

1. It is unclear why reko sees here a char pointer.
2. The condition should be inverted to avoid the else branch.

**Comment by uxmal** [comment]
After commit, d72c8a33a7dad5c430520ac89c536fe9c78166b7, Reko no longer is confused by the tail call to `printf`. However, since the parameters `s` and `u` are receiving their values from the same variable in `main`, Reko puts them in the same equivalence class, which results in `s` and `u` getting the type `union { int32_t a; uint32_t b; }`.

I'm curious how holdec avoids merging the two equivalence classes of `s` and `u` -- perhaps you could give a little detail here?

**Comment by uxmal** [comment]
I'm closing this now, but am still curious about holdec's handling of the equivalence classes. If you're interested in discussing this, reach out to me by email or gitter.im.
