### ISSUE TITLE
Add the ability to add comments tothe code and assembly

### ISSUE THREAD

**Issue by Cairn23** [uxmal/reko#604]
It would be good to have the ability to place comments against the lines of code /assembly of the de-compiled binary. Add the comment in the assembly window "; my comment"would also add the same comment in the C code window in C type syntax " // my comment". This comments would be saved in the project file so could be reviewed / updated later

**Comment by uxmal** [comment]
Some things that need to happen to make this work.
- [ ] Add a `CodeComment` class so that comments that have been added to the code are not lost as Reko performs its analyses on `Procedure`s.
- [ ] Modify the Reko project file format so that user comments are tracked. This will probably be `Dictionary<Address, string> Comments`.
- [ ] When a procedure is scanned the `Scanner` must be aware of the user comments and inject them into the generated IR code.
- [ ] Users expect to see the comments both in the `DisassemblyView` and the `CodeView`. The latter is easy, just implement `CodeComment` above. However, in the disassembly view we may need to change the way it renders so that comments can be acommodated.
- [ ] Users expect to be able to click on an address and create a comment there.
- [ ] Users expect to be able to click on comments and edit them.
- [ ] Users expect to be able to remove comments
- [ ] Comments in assembly language traditionally use `;` as the introducing character, but some assemblers may use different characters. This is a platform-dependent property, but for now we can simplify our lives and just use `;` until a user comes with a request.
- [ ] Similarly, the output language may dictate the comment syntax. This will be taken care of by the abstract syntax stage.
- [ ] Comments should be treated as multiline.

**Comment by uxmal** [comment]
Some more work items:
- [ ] If a user adds a comment in the CodeView, we expect it to also be added as an `Annotation` in the program's `UserData`. If the user edits or removes it, we expect the obvious thing to happen there too. Same applies to comments added to the Disassembly View.

**Comment by ptomin** [comment]
![3](https://user-images.githubusercontent.com/13188041/38381422-2a0eca8c-3920-11e8-83f9-75168c5c67b3.jpg)

**Comment by Cairn23** [comment]
In terms of were the comment should be placed, going back to my assembly days, we would place a comment against each line of assemble at the end of the line so would look like:
00401031 8B EC         mov      ebp, esb          ; copying value across

This would then look like real assemble listings

and in the C code you would see something like
a = b  // copying value across

**Comment by Cairn23** [comment]
Oh, for multiple comment lines it would look like

00401031 8B EC mov ebp, esb ; copying value across
                                                  ; and I need to extend the comment to
                                                  ; really explain what I am doing here

**Comment by Cairn23** [comment]
The multiple example has not worked well the second and third lines should be below the first

**Comment by ptomin** [comment]
But placing comments above line is correct, too. Is not it? And it would easier to view them. There is no additional place at the right is needed

**Comment by uxmal** [comment]
I've checked some more items. All we need to do now is be able to delete comments. Are you up for it? :)

**Comment by ptomin** [comment]
I suggest to remove comments when user inputs empty comments rather than creating corresponding menu item

**Comment by uxmal** [comment]
makes sense. Go ahead and implement that.

**Comment by ptomin** [comment]
I'll implement it this evening

**Comment by uxmal** [comment]
PR #617  merged this into `master`. You should be able to pick up a fresh steaming binary from https://ci.appveyor.com/project/uxmal/reko/build/artifacts
