### ISSUE TITLE
m68k jump tables decompilation is unstable

### ISSUE THREAD

**Issue by wdigger** [uxmal/reko#691]
This issue related to #121.
Jump tables not always detected while decompiling.
Here is [test.zip](https://github.com/uxmal/reko/files/2407799/test.zip) a sample project, function `update` contains two cases - right and wrong.
I would like to understand the problem myself, but I need an initial push - where does recognition of such patterns take place?

**Comment by ptomin** [comment]
> I need an initial push - where does recognition of such patterns take place?

Indirect jumps are resolved during scanning phase. See
https://github.com/uxmal/reko/blob/a9d242910cd0e7f8e5d8e399507f7a319e2e26e9/src/Decompiler/Scanning/BlockWorkitem.cs#L917

**Comment by wdigger** [comment]
@ptomin thanks! But it's look like problem happened earlier. Disassembler stop translate code after jump in bad case. But I don't see any difference between those cases.

**Comment by uxmal** [comment]
I'm always interested in fixing failures at scan time. Unfortunately I'm AFK and won't be able to look at your binary until later tonight

**Comment by uxmal** [comment]
I've fixed the flaw, but it turns out that this binary -- which I suspect was at least partially written by hand in assembler -- has logic that looks something like this (expressed in Reko's RTL);
```
d0 = d0 - 0x20
if (d0 < 0) branch somewhere_else

d0 = d0 * 4
goto start_label + d0

start_label:
goto case_0x20 // these goto instructions are 4 bytes in 68k machine code
goto case_0x21
goto case_0x23
// a few more of these
```
The programmer must be assuming that the value in d0 is bounded above by some value. However, that upper bound is not present in the actual machine code. It is instead establishing a _lower_ bound, 0x20. The result is that Reko has to (over)estimate that 0x20 <= d0 < MAX_INT, which is very pessimistic.

Without a heuristic analysis, Reko can't go further than deducing that since an indexed indirect jump is being made, the intent is that there are more than one jump target. The MAX_INT upper bound is clearly wrong and can be detected, but we have to be conservative and limit the number of jump targets to two (unless the user specifies exactly how many targets there are).

I will push my fix shortly, which will at least discover two of the branches, and then will have to look at if there is anything that can be done to discovering the remaining branches. I suspect this will have to rely on some form of pattern matching.
