### ISSUE TITLE
Discussion MACOS - function simplified to constant 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#727]
I have a function that checks whether the cpu is big/little endian. 

﻿00101C28 4E56 FFFC link a6,#$FFFC
00101C2C 3D7C 0001 FFFC move.w #$0001,-$0004(a6)
00101C32 102E FFFC move.b -$0004(a6),d0
00101C36 1200 move.b d0,d1
00101C38 7000 moveq #$00,d0
00101C3A 1001 move.b d1,d0
00101C3C 4E5E unlk a6
00101C3E 4E75 rts 

after processing it get simplified to the following.

﻿int32 CheckCPUEndian()
{
    return 0x01;
}

While in the 68K code context this function does simplify to a constant "1" (big endian), the current output has lost the original function. If this output is then compiled for use on a different platform with a little endian cpu, the behaviour of that function would be incorrect and any use of that function within the program would likely impact processing and output. 

Just an observation and glad to discuss.

**Comment by uxmal** [comment]
How interesting! It turns out there are two separate issues manifesting here. The first issue is a bug. You've cleverly exposed Reko's strong little-endian bias. There are a lot of places where little endian assumptions are being made in the code base and which only are exposed when tested with big-endian processors like M68k or SPARC. The second issue is a consequence of the aggressive constant propagation Reko needs to do to properly analyze binaries.

I will rewrite your code into simplified Reko IR for ease of discussion. The following code is what gets generated after SSA conversion (ignoring the `a6` frame setup instructions which don't play a part in the problem at hand):
```
int32 IsLittleEndian() {
    Mem2[fp - 4:word16] = 0x0001    ; Initial write
    v3 = Mem2[fp - 4:word16]        ; Aliased read
    d0_4 = DPB(d0, v3, 0)
    d1_5 = d0_5
    d0_6 = 0x00000000
    d0_7 = DPB(d0_6, (byte)d1_5, 0)
    return d0_7
}
```
The two memory accesses are not referring to the same exact memory location: the one labeled `Initial write` is writing the 16-bit word 0x0001 to addresses `fp - 4` and `fp - 3`. Depending on the endianness, this results in either `01 00` (little-) or `00 01` (big-endian) at `fp - 4`. The memory access `aliased read` reads the byte at `fp - 4` which will be either `01` (little-) or `00` (big-endian). The read byte is then zero extended and returned to the caller.

One of the things Reko does is convert frame accesses like `Mem[fp - 4]` into identifiers like `wLoc04`. Applying that transformation to the procedure, Reko mistakenly generates:
```
    wLoc04 = 0x0001                 ; Initial write
    v3 = (byte) wLoc04              ; Aliased read
    ...
```
where, for big-endian machine code, it should be generating
```
    wLoc04 = 0x0001                 ; Initial write
    v3 = SLICE(wLoc04, byte, 8)     ; Aliased read
```
This bug should be easy to fix in the `analysis-development` branch of Reko. I will add a unit test with your code in it and make it work.

Now we have to reason about the constant propagation part. The two (corrected) instructions above will be aggressively (and correctly, I claim) simplified to:
```
    wLoc04 = 0x0001
    v3 = SLICE(0x0001, byte 8)
```
which simplifies further to:
```
    wLoc04 = 0x0001
    v3 = 0x00
```
and after all the other statements are also simplified:
```
int32 IsLittleEndian() {
    return 0;
}
```
...which is correct for a M68k machine!

It's clear that the machine code was generated by a compiler that didn't optimize aggressively. Otherwise, the M68k machine code would have been generated as 
```
    movq #00,d0
    rts
```
In a way, Reko is performing the optimization for that old compiler! 

But by optimizing this aggressively, we are losing the (unoptimized) logic that performed the detection. If we want to preserve that logic, we clearly need to prevent Reko from optimimizing away the assignments to the memory.

We cannot totally disable constant propagation: it's critical for the operation of the data flow analys passes. However, it might be possible to add a feature to mark a particular memory location as 'volatile' or 'aliased'. Doing so would stop the propagation and generate code like:
```
    wLoc04 = 0x0001
    v3 = *((byte *) &wLoc04)
```
which would be more faithful to the original code. This type of type punning is valid in C, but invalid C++.

**Comment by gbody** [comment]
Glad I was able to give you with something interesting.
Those two lines are pretty much correct the original function.

**Comment by uxmal** [comment]
I believe commit 2db5384 addresses this. Let me know if you see other regressions.
