### ISSUE TITLE
Exceptions when reading from file and a file cannot be opened at all, probably endless loop

### ISSUE THREAD

**Issue by 0xBEEEF** [uxmal/reko#730]
I have an example [here](http://pod.nicode.net/patches/21_pvr-2.zip), which I tried to read in just for the sake of trying. I noticed that I can read the DLL contained in the ZIP archive relatively problem-free. I can also read the smaller exe file, but there are some exceptions which are displayed in the diagnostic window. I cannot read the larger Exe file at all. Here the program does not react any more. It looks as if there is an endless loop somewhere.

**Comment by uxmal** [comment]
Thanks for reporting this. I will take a peek at this in a couple hours.

**Comment by uxmal** [comment]
What build are you testing this with, and which environment? I ran the most recent Reko builds, both command line and GUI client, on Windows 10. On all runs I was able to run to completion, albeit with some warnings and errors in the diagnostics window.

**Comment by 0xBEEEF** [comment]
I used the last released version (0.8) for my tests, also on Windows 10. And here I had the problem with the big EXE file that the system was completely frozen and never came back. I tried both the command line and the GUI version. In both cases the exact same behavior...

**Comment by uxmal** [comment]
That tells me a release is due. For the time being follow the instructions on the README.md and download Reko ready to run from AppVeyor

**Comment by 0xBEEEF** [comment]
Thanks for the hint! I got the last build on AppVeyor, so loading the file works without any errors! Unfortunately there are still some errors in the "Diagnosis" window. Do you still want to have a look at them? At least you can read the files now without any problems, and maybe the files will help you to make your program even better.

**Comment by uxmal** [comment]
A quick glance at the errors I get when I load those binaries tells me that the majority are known from before. Some look   unfamiliar though,  so I will take some time this evening and investigate closer.

**Comment by 0xBEEEF** [comment]
Thanks! Oh, what else I've generally noticed: There are a lot of strings and other constants in the binary files, but they don't really appear in the output. I have already seen other cases in the issues where the strings were recognized and assigned without problems. Is this also a bug, or is it just not implemented yet? Furthermore, the data type analysis only works correctly for simple data types, complex structures don't seem to have been recognized. What I would find super cool would be if, similar to Snowmen with the -> and . operator would be used to access structures. That would be somehow better readable than always the Mem[xyz]. Is this planned for the long term? I know the automatic recognition and/or editing of structures is the supreme discipline.

**Comment by uxmal** [comment]
By default, Reko uses recursive disassembly to locate procedures in the binary. Procedures that are only ever called indirectly (e.g. via vtables or other kinds of function pointers) will not be detected. I noticed that when I ran Reko on your binary, it only finds a handful of functions. There is a feature, which regrettably is not easily discoverable, which makes Reko perform a "shingle scan" across the binary. This typically finds a more procedures than recursive disassembly alone. To perform shingle scanning, you can right-click on the executable in the project browser tree, select `Properties`, switch to the `Scanning` tab, and select `Shingle heuristic` before proceeding with `Scan binaries`. 

Reko tends to be rather conservative about detecting strings. Unless it can prove that a value is used as a string, it won't attempt to mark it as such. If so little of the program code has been recovered (e.g. because shingle scanning has not been turned on) that no string pointers are found, no strings will be retrieved. I've been considering adding an optional "guess strings" pass, which would perform a scan to find sequences of `N` or more valid code units (be it ASCII, UTF-8, etc) and retrieve strings this way. Perhaps this would be satisfactory for you?

Today Reko actually does type recovery as a global analysis; it can discover arrays of structures, pointers to structures, etc. but only after the previous scans complete. If a exception happens during type recovery, regrettably everything is dropped on the floor. I want to change this behavior so that type recovery can be done incrementally and be more robust to crashes.

**Comment by 0xBEEEF** [comment]
Many thanks for the detailed answer! I am impressed by your commitment! Yes, I think it would be a great idea if strings would have been better recognized in the future, because there are a lot of them after all. Maybe you could also provide a list of strings, similar to IDA. If you open the EXE files there, you'll see right away that there are really a lot of strings included. Oh, I have another question about the external methods. With the binary files provided by me there is a warning in many external methods that the resolution of the function was not successful. The functions then appear parameterless in the final result.

Regarding the structures. I've tried this before in a mini example, and I have to say that I think it's really great if it works completely. The operators I mentioned above are indeed visible, and the readability is significantly increased. But this doesn't seem to work with the binaries provided above. Something still causes errors there.

All in all, however, I can already say that I am very impressed by the results. What you analyze in a very short time from any program and create for readable code is really impressive. If you compare this with the results of RetDec or Snowman, the result is already better than Snowman and many times better than RetDec. Pretty impressive.

**Comment by uxmal** [comment]
Thanks for the kind words. I and the other folks working on Reko want to have a performant and useful decompiler for people to use. It's encouraging to read feedback like yours.

Some final notes: Reko supports adding "metadata" files, like C header files, using the `File > Add metadata` menu. If you do this, Reko should be able to resolve all those external functions. One potential difficulty is that Reko's C parser can't really cope with modern C++ header files very well yet.
That should take care of most of the warnings you are seeing.

After Reko has loaded the binary, you should test the `View > Find strings...` menu, which sweeps through the program looking for strings. You can then mark those strings that are "real". I just noticed a small bug there that I will be addressing during the weekend.
