### ISSUE TITLE
MacOS - unexpected output " / 0x0010" generated

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#736]
Looking further through the output for the sample file - linkiigs

I have found the output dwArg04[d7_17 / 0x0010] in the decompiled code. In the example I have included it appears as part of the index into a char array. 

What I don't understand is where the extra " / 0x0010" are coming from. These extra " / 0x0010" appear in multiple places throughout the output which appear to me to be unexpected.

Example
============================================
Disassembled 68K Code fragment

;; upper: 0010371E
upper proc
	link	a6,#$0000
	movem.l	d7/a4,-(a7)
	movea.l	$0008(a6),a4
	moveq	#$00,d7
	bra	$00103746

l0010372E:
	move.b	(a4,d7),d0
	ext.w	d0
	ext.l	d0
	move.l	d0,-(a7)
	jsr.l	$21C4(pc)        ; 001058FC (toupper)
	move.b	d0,(a0,d7)
	addq.w	#$04,a7
	move.l	d7,d0
	addq.l	#$01,d7

l00103746:
	tst.b	(a4,d7)
	bne	$0010372E

l0010374C:
	movem.l	-$0008(a6),d7/a4
	unlk	a6
	rts	
00103756                   85 75 70 70 65 72 00 00             .upper.. 

==============================================
Decompiled code fragment for the same function

// 0010371E: void upper(Register (ptr32 Eq_5) a0, Stack (ptr32 Eq_5) dwArg04)
void upper(Eq_5 * a0, Eq_5 * dwArg04)
{
	int32 d7_17 = 0x00;
	while (dwArg04[d7_17 / 0x0010] != 0x00)
	{
		a0[d7_17 / 0x0010] = (struct Eq_5) (byte) toupper((int32) (int16) dwArg04[d7_17 / 0x0010]);
		++d7_17;
	}
}

**Comment by uxmal** [comment]
Sorry I haven't got back to you earlier. This looks like overzealous compensation for array indices. The type inferences has likely incorrectly  deduced that `Eq_5` has a size of 16 bytes, and in every array access of the form `Mem[dwArg04 + d7_17]`, `d7_17` is being downscaled to make it an appropriate index. 

The underlying cause is that `Eq_5`; for some reason, `upper` (which seems to be manipulating a string of byte-sized characters) has incorrectly been assigned a signature of non-characters.

The `.h` file Reko outputs contains debugging information about equivalence classes. All of the type variables that are part of the same equivalence class are listed there. One or more of them must have forced the size to be 16. I will look at this tonight my time to see if there is something obvious I can do to fix this.

**Comment by uxmal** [comment]
Update: working on getting this fixed on `analysis-development` branch, I'm now deep in the warren of rabbit holes :) Turns out that the Pascal parser was incomplete; it didn't know about `boolean` nor Pascal variant records. Neither does it know how to calculate accurate sizes for data structures. These sub-issues have to be fixed before progress can be made on this isssue.

**Comment by uxmal** [comment]
This no longer appears after commit 1fb5a6faac99b36413fdfb036134c775dd8441c7 in the `analyis-development` branch.
