### ISSUE TITLE
Move to .net core

### ISSUE THREAD

**Issue by Cairn23** [uxmal/reko#748]
Yes move again! The only reason for suggesting this is that it will remove issues going ahead, something that could be done on small blocks, does not need a big bang approach, and will also provide a UI that (WFP) that could be used going forward

**Comment by uxmal** [comment]
The development branch for moving to .NET Standard is called `netStandard`: https://github.com/uxmal/reko/tree/netStandard

All of the projects have been ported to the new `.csproj` format, now it's stalled because I haven't had the time to look unto why properties / properties are not being set as expected when I run `msbuild`. Contact me on gitter if you wish to help here.

**Comment by uxmal** [comment]
We're currently blocked on dotnet/runtime#43675. The XML serializer has a bug that causes Reko to crash on startup. I hope Microsoft are kind enough to provide a fix for this, but at the time of writing, they've triaged it to .NET 6... November 2021 :(

**Comment by uxmal** [comment]
Commit e7617cd works around the issue with dotnet/runtime#43675. It (temporarily) disables the unit tests that are triggering a bug deep in the bowels of the `XmlSerializer` in .NET Core 3.1 and .NET 5.

We've disabled the GUI components for the `UnixRelease` build, as it seems impossible to build Windows Forms on Linux.

Currently, there are icons missing in the main toolbar. Once those are fixed, I think we're finally ready to merge this to `master`.

**Comment by uxmal** [comment]
At long last, the `netStandard` branch has been merged to `master`.
