### ISSUE TITLE
Internal error / divide by zero

### ISSUE THREAD

**Issue by kimstik** [uxmal/reko#825]
happen on simple HEX file from https://electrosome.com/wp-content/uploads/2013/05/LED-Blinking-with-8051-Microcontroller-and-Keil-C-AT89C51.zip
when pressed "Analyze dataflow"

WindowsDecompiler-0.9.0.0-1d0a14bd17.zip from https://ci.appveyor.com/project/uxmal/reko/build/artifacts

**Comment by uxmal** [comment]
The division by zero has been resolved. I've fixed a few other issues that were preventing decompilation of your HEX file.

The root cause was that the HEX file you provided has no start address defined. There is nothing wrong with this per se, but it means Reko doesn't know where the code is. You can assist Reko by doing the following:

* Find the start procedure in the memory viewer, either by visually scanning for it or using the tools in the `Edit` and `View` menus to locate patterns in the binary. 
* Once the start address is located, right-click on it and select `Mark as procedure`.
* Push the `Finish decompilation` button.

Alternatively, you could modify the HEX file and add a record of type `05` ("Start linear address") to indicate where the start address is. Then the manual steps above become redundant.

I've taken the liberty of adding your HEX file to Reko's regression suite, along with a `dcproj` file containing the start address. The resulting C code is can be viewed here: https://github.com/uxmal/reko/blob/master/subjects/i8051/reko-825/ledwith8051.reko/ledwith8051.c
