### ISSUE TITLE
Errors when attempting to decompile

### ISSUE THREAD

**Issue by valley-fordham** [uxmal/reko#832]
Hi,

I'm messing about with your decompiler and an old 16-bit MS-DOS executable, and struck some errors when trying it out.

The issue may already be reported and fixed [here](https://github.com/uxmal/reko/issues/821) but in case it hasn't...
```
Error,0816:2001,An error occurred while processing the statement word16 ax_453 = ax_442 - ax_206. Pulling difference ptr16 and (union (int16 u0) (uint16 u1)) 
Error,fn0816_03A4,An error occurred while rewriting procedure to high-level language. Expression of type Slice doesn't support Invert. 
```
Binary can be downloaded [here](https://drive.google.com/open?id=1I1xvesCgUiOPpzAMeTHi29BZier8HAOK).

This binary is an entry point to another binary so doesn't do much on its own. Happy to provide the main binary it links to if that would be useful.

Cheers!

**Comment by uxmal** [comment]
Thanks for taking the time to report this! The `Expression of type Slice...` was fixed in the issue you refer to. The other error you are seeing should be a warning; the type inference module proceeds with the rest of the program after encountering that.

If you cannot build Reko yourself, you can get a steaming fresh build of Reko by downloading the files from the CI server at AppVeyor:
https://ci.appveyor.com/project/uxmal/reko/build/artifacts
