### ISSUE TITLE
Improvements for Xtensa arch

### ISSUE THREAD

**Issue by Piruzzolo** [uxmal/reko#839]
I'm trying to reverse the Espressif's precompiled WiFi stack for the ESP32.
Looks like many Xtensa instructions are not implemented and none of the library functions are recognized. Possibly other issues. Ghidra has a plugin for it not yet merged, you may check against it (see its GitHub ~~issues~~ PRs)

Note to reproduce: extract .a files with 7zip, then load .o files.

** EDIT ** note that Ghidra's plugin misses some instructions

**Comment by uxmal** [comment]
I find it helpful to focus on a particular binary -- how about https://github.com/espressif/esp32-wifi-lib/blob/master/esp32/librtc.a?

**Comment by Piruzzolo** [comment]
I've tried libnet80211.a, but any of those should be fine :D

**Comment by uxmal** [comment]
@Piruzzolo: Reko now disassembles all documented Xtensa instructions. It will convert all but a handful of them to IR. The remaining ones are the `LOOP` family and the `CALLnn` family, which have odd semantics I need to study further. I haven't tested them on the archive yet, but you should get slightly better results.

I hope to have the remaining instructions finished in the coming week. Keep watching this issue for updates.

**Comment by Piruzzolo** [comment]
That's great! Trying asap, thank you dude! Your work sincerely amazes me! ✌️

**Comment by uxmal** [comment]
The Xtensa ISA is now completely implemented. I will close this issue now, but I encourage you to report any other issues you encounter as you use Reko on your test binaries.

**Comment by Piruzzolo** [comment]
Thanks man! Good job! I'm looking at the the disassembly, what does "reserved" mean?

**Comment by uxmal** [comment]
`reserved` is the term Xtensa uses for opcodes that don't have a defined implementation. Other architectures call these `invalid` or `illegal`. It means that the bytes at that address don't correspond to a meaningful instruction, either because you're disassembling data, or -- on instruction set architectures with variable instruction lengths like Xtensa or x86 -- the disassembler is not aligned with the instruction stream.

Thanks for pointing out the broken unit test; my latest push should address the problem.
