### ISSUE TITLE
Add button to save exported functions from a library

### ISSUE THREAD

**Issue by claunia** [uxmal/reko#846]
Add a button so a DLL can be opened and we can get a tuple (moduleName, ordinal, functionName) exported to CSV/JSON/XML.

**Comment by claunia** [comment]
XML is preferred over JSON but if it is easy to add a selector better. The more the merrier.

**Comment by uxmal** [comment]
Commit c5cbe2d implements a variation of this. Reko will always generate a file of exported functions, using whatever file format that is appropriate for a specific `Platform`. For 16-bit OS/2, I think module definition files are appropriate (`.def` file extension), since they were used to export functions from DLLs. Happily, Reko already supports reading module definition files. Now the user won't need to make an extra GUI gesture to obtain this information.
