### ISSUE TITLE
x86-16 Fails to associate memory accesses with globals

### ISSUE THREAD

**Issue by blindmatrix** [uxmal/reko#864]
[DSbug.zip](https://github.com/uxmal/reko/files/4672426/DSbug.zip)
[not-a-fix-fix.txt](https://github.com/uxmal/reko/files/4672441/not-a-fix-fix.txt)

Included is an Open Watcom project that demonstrate this issue.

After registering a global (and forcing DS to DGROUP) the access is decompiled to seg1046->w0060 instead of globals->theGlobal.

A patch is also included that's not a proper fix, but at least make the issue go away.

**Comment by uxmal** [comment]
Commit 7aa3189 is the first part in supporting globals in segmented programs (meaning MZ-EXE and NE executables). The next step, which is something that has been postponed for some time, is changing the way that global variables are rendered in Reko.

Today they are rendered using the class `GlobalDataWriter` into a separate file, `file.globals.c`. This wasn't working at all with segmented binaries because they don't have linear addresses, but instead segmented addresses. The `GlobalDataWriter` would need to be changed to handle cases where segmented pointers in one segment refer to objects in another segment. `GlobalDataWriter` wasn't designed to deal with the multiple file support this would require.

To fix this, we have to change the `OutputFilePolicy` class so that it can apply a placement policy to global data objects as well as procedures. In order to accomplish this, we need a first pass that discovered all the global variables. This is half of what `GlobalDataWriter` does: it traces the `Program.GlobalFields` structure, recursively chasing all pointers until all reachable objects have been located, and rendering them. Chasing the pointers allow it to locate all data object that aren't referred directly in the code of the decompiled program.

I'm moving the "tracing" capabilities of `GlobalDataWriter` into a separate class, tentatively called `GlobalDataTracer`. Once the addresses and objects are collected, the `OutputFilePolicy` can use the collection of (address, object type, object name) gathered by the `GlobalDataTracer` to place the objects in different files depending on the placement policy.

**Comment by uxmal** [comment]
The fix to this issue is now in the `master` branch.
