### ISSUE TITLE
i386: Improve sub register evaluation

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#895]
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/dmi/value_prop/ia32_elf/
Method: intermediate_10_subregs

Source:
```
intermediate_10_subregs:
        mov     global_char1, %ah
        mov global_char2, %al
        mov %ax, %bx
        mov %ebx, %ecx
        mov %ecx, %eax
        add %ah, %ah
        add %al, %al
        add %al, %al

        movzbl %al, %ebx
        movzbl %ah, %ecx
        mov $0, %eax
        add %ebx, %eax
        add %ecx, %eax
        pushl %eax
        call putchar
        xorl    %eax, %eax
        addl    $4, %esp
        ret
```

Output:
```
word32 intermediate_10_subregs(ptr32 & ebxOut)
{
	word32 ebx_10 = SEQ(ebx_16_16, SEQ(g_b804A030, g_b804A031));
	ptr32 ebx_18 = (word32) ((byte) ebx_10 * 0x04);
	putchar(ebx_18 + (word32) (SLICE(ebx_10, byte, 8) * 0x02));
	ebxOut = ebx_18;
	return 0x00;
}
```

Expected output: something like (plus maybe some casts)
```
int intermediate_10_subregs()
{
  putchar(2 * global_char1 + 4 * global_char2);
  return 0;
}

**Comment by uxmal** [comment]
After commit dfa33c3d0e8000f14734e64eec5da515d51ca9fb, Reko's output looks like this:
```C
word32 intermediate_10_subregs(ptr32 & ebxOut)
{
    ptr32 ebx_18 = (word32) (g_b804A031 * 0x04);
    putchar(ebx_18 + (word32) (g_b804A030 * 0x02));
    ebxOut = ebx_18;
    return 0x00;
}
```
The `ebx_18` variable is forced live because `ebx` is erroneously live-out, due to the violation of the calling convention mentioned above. Your `main` procedure is compiled with a compiler that does respect the ABI and assumes that the caller doesn't trash `ebx`. The `main` procedure uses `ebx` to accumulate the answers from the subroutines it calls, but because `intermediate_10_subregs` violates the ABI, `ebx` is trashed and the output is wrong. 

Reko is probably providing the best output of all decompilers here, given the state of the binary.
