### ISSUE TITLE
Interprocedural jumps confuse Reko scanner

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#90]
At this file there are many errors starting from the second step.
[PP.zip](https://github.com/uxmal/reko/files/71704/PP.zip)

**Comment by uxmal** [comment]
Thanks for reporting this. I am currently away on holiday but will look into this when I get back.

**Comment by uxmal** [comment]
(changed the title from: "MS-DOS and decompilation errors"). The root cause of the errors here is a large number of cross procedure jumps in the provided binary. The reko scanner makes a weak attempt at handling this, but in order to fix the issue I will require some serious thinking about how to handle this "the right way". 

The principal difficulty is that the reko scanner is responsible for building `Procedures` from basic blocks. The cross-procedure jumps violate some central assumptions the scanner is depending on.

As mentioned, I'm on holiday and can't focus too much on this just now but will hopefully think of something after returning home.

**Comment by uxmal** [comment]
At long last, this issue has been fixed. The indirect jumps no longer cause crashes.
