### ISSUE TITLE
Should load floating point values from read-only section

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#922]
Subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_boomerang/testfp/ia32_elf_by_boomerang

Current output
```
void main()
{
	__align(fp - 0x0C);
	printf("Hello, world\n");
	g_t80497D0 = (real64) g_w80486C4 - (real64) g_w80486C0;
	printf("Result is %f\n", SEQ(g_dw80497D4, g_t80497D0));
	g_t80497D0.u0 = (real64) g_w80486C0;
	printf("Result is %f\n", SEQ(g_dw80497D4, g_t80497D0));
...
```

Issues:
- Should load the concrete values (3.0 and 5.0) from the memory locations and compute concrete results
- The value (`SEQ(...)`) passed to `printf` should be prettier.

**Comment by uxmal** [comment]
With the commit above, the SEQ's are gone:
```C
void main()
{
	__align(fp - 0x0C);
	printf("Hello, world\n");
	g_r80497D0 = (real64) g_w80486C4 - (real64) g_w80486C0;
	printf("Result is %f\n", g_r80497D0);
	g_r80497D0 = (real64) g_w80486C0;
...
```
However, I think the casts should remain, because they're conveying what the program is actually doing. These are not concreate floating point constants being loaded. The variable `g_w80486C4` is actually a 16-bit word, and the program then casts it to a 64-bit float. It's another case of weighing off being faithful to the original binary or optimizing aggressively. 

Had the globals been floating point constants and not integer constants being cast to floating point, I'd have less of an issue with it. You've filed another issue elsewhere that brings it up; I hope to address that shortly.

**Comment by rfalke** [comment]
The casts can remain but the constants should still be part of the output:
```
  g_r80497D0 = (real64) 5 - (real64) 3;
```
