### ISSUE TITLE
reko v0.9.2.0 fails on Windows XP SP3

### ISSUE THREAD

**Issue by LordGarfio** [uxmal/reko#994]
reko v0.6.2.0 works fine on Windows XP, but since v0.7.0.0 till up v0.9.2.0 no longer.

Is there a way to support Windows XP again ?

**Comment by uxmal** [comment]
How exactly is Reko failing on Windows XP? Are you getting error messages? Do you have .NET Framework 4.7.2 installed? 

Since Windows XP is no longer a supported version of Windows, it's unlikely that we will make a big effort to make it work on that platform. I recommend Windows 7 or later. An upcoming version of Reko will switch over to .NET Core 3.1. I'm not certain if .NET Core 3.1 is supported on Windows XP, but it is supported on various Linux distros and MacOS.

**Comment by LordGarfio** [comment]
Last MONO version with support for Windows XP SP3 is v4.3.2.467 and that does not replace .NET 4.5

mono-4.3.2.467-gtksharp-2.12.30.1-win32-0.msi
mono-4.3.2.467-x64-0.msi
https://download.mono-project.com/archive/4.3.2/windows-installer/

Last .NET Framework for Windows XP SP3  v4.0.3
dotNetFx40_Full_x86_x64 .NET Framework v4.0.0 Setup
NDP40-KB2600211-x86-x64.exe .NET Framework v4.0.3 Upgrade Setup

Therefore .NET Framework 4.7.2 can not install on Windows XP.

Thanks you anyway.
